name: Deploy vcrypto trading

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout
       uses: actions/checkout@v1

      - name: configure AWS Credentails
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/vcrypt-project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
